language: node_js

branches:
  only:
    - master

cache:
  directories:
    - node_modules

node_js:
  - '7'
  - '6'

install:
  - npm install -g firebase-tools
  - npm install

script:
  - npm run build
  - firebase deploy --token ${FIREBASE_TOKEN} --non-interactive
