language: node_js

branches:
  only:
    - master

cache:
  directories:
    - node_modules

node_js:
  - '7'
  - '6'

install:
  - yarn global add firebase-tools

script:
  - rm -f src/config.js
  - mv src/configDeploy.js src/config.js
  - yarn build
  - firebase deploy --token ${FIREBASE_TOKEN} --non-interactive
